### ISSUE TITLE
Conflict with DiffEqFlux.jl

### ISSUE THREAD

**Issue by yaomz16** [zygmuntszpak/ImageComponentAnalysis.jl#26]
Hi, 

I was trying to install DiffEqFlux.jl into my JuliaImage environment: 

(ImageTest) pkg> st
      Status `......Project.toml`
  [052768ef] CUDA v3.5.0
  [cbc4b850] ImageBinarization v0.2.7
  [d9b9e9a0] ImageComponentAnalysis v0.1.0
  [6218d12a] ImageMagick v1.2.1
  [916415d5] Images v0.24.1
  [5e47fb64] TestImages v1.6.1
  [de0858da] Printf
and get the following error when installing the DiffEqFlux:

(ImageTest) pkg> add DiffEqFlux
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DistributionsAD [ced4e74d]:
 DistributionsAD [ced4e74d] log:
 ├─possible versions are: 0.1.0-0.6.31 or uninstalled
 ├─restricted by compatibility requirements with StatsBase [2913bbd2] to versions: [0.1.0-0.3.2, 0.4.9-0.6.31] or uninstalled
 │ └─StatsBase [2913bbd2] log:
 │   ├─possible versions are: 0.24.0-0.33.11 or uninstalled
 │   ├─restricted by compatibility requirements with Images [916415d5] to versions: 0.24.0-0.33.11
 │   │ └─Images [916415d5] log:
 │   │   ├─possible versions are: 0.17.3-0.24.1 or uninstalled
 │   │   ├─restricted to versions * by an explicit requirement, leaving only versions 0.17.3-0.24.1
 │   │   └─restricted by compatibility requirements with StatsBase [2913bbd2] to versions: 0.22.1-0.24.1 or uninstalled, leaving only versions: 0.22.1-0.24.1
 │   │     └─StatsBase [2913bbd2] log: see above
 │   └─restricted by compatibility requirements with Flux [587475ba] to versions: 0.33.0-0.33.11
 │     └─Flux [587475ba] log:
 │       ├─possible versions are: 0.4.1-0.12.7 or uninstalled
 │       ├─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.4.1-0.10.4, 0.11.2-0.12.7] or uninstalled
 │       │ └─CUDA [052768ef] log:
 │       │   ├─possible versions are: 0.1.0-3.5.0 or uninstalled
 │       │   ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-3.5.0
 │       │   └─restricted by julia compatibility requirements to versions: [2.3.0, 2.5.0-3.5.0] or uninstalled, leaving only versions: [2.3.0, 2.5.0-3.5.0]
 │       ├─restricted by compatibility requirements with DiffEqFlux [aae7a2af] to versions: 0.4.1-0.12.7, leaving only versions: [0.4.1-0.10.4, 0.11.2-0.12.7]
 │       │ └─DiffEqFlux [aae7a2af] log:
 │       │   ├─possible versions are: 0.0.1-1.43.0 or uninstalled
 │       │   ├─restricted to versions * by an explicit requirement, leaving only versions 0.0.1-1.43.0
 │       │   ├─restricted by compatibility requirements with Adapt [79e6a3ab] to versions: [0.0.1-0.4.0, 1.13.0-1.43.0] or uninstalled, leaving only versions: [0.0.1-0.4.0, 1.13.0-1.43.0]
 │       │   │ └─Adapt [79e6a3ab] log:
 │       │   │   ├─possible versions are: 0.3.0-3.3.1 or uninstalled
 │       │   │   └─restricted by compatibility requirements with CUDA [052768ef] to versions: 2.2.0-3.3.1
 │       │   │     └─CUDA [052768ef] log: see above
 │       │   ├─restricted by compatibility requirements with Flux [587475ba] to versions: 1.18.0-1.43.0 or uninstalled, leaving only versions: 1.18.0-1.43.0
 │       │   │ └─Flux [587475ba] log: see above
 │       │   ├─restricted by compatibility requirements with Reexport [189a3867] to versions: [0.0.1-1.38.0, 1.40.0-1.43.0] or uninstalled, leaving only versions: [1.18.0-1.38.0, 1.40.0-1.43.0]
 │       │   │ └─Reexport [189a3867] log:
 │       │   │   ├─possible versions are: 0.2.0-1.2.2 or uninstalled
 │       │   │   ├─restricted by compatibility requirements with CUDA [052768ef] to versions: 0.2.0-1.2.2
 │       │   │   │ └─CUDA [052768ef] log: see above
 │       │   │   └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: 0.2.0
 │       │   │     └─DataFrames [a93c6f00] log:
 │       │   │       ├─possible versions are: 0.11.7-1.2.2 or uninstalled
 │       │   │       └─restricted by compatibility requirements with ImageComponentAnalysis [d9b9e9a0] to versions: 0.19.4
 │       │   │         └─ImageComponentAnalysis [d9b9e9a0] log:
 │       │   │           ├─possible versions are: 0.1.0 or uninstalled
 │       │   │           └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0
 │       │   └─restricted by compatibility requirements with DiffEqSensitivity [41bf760c] to versions: 1.0.0-1.39.0 or uninstalled, leaving only versions: 1.18.0-1.38.0
 │       │     └─DiffEqSensitivity [41bf760c] log:
 │       │       ├─possible versions are: 2.0.0-6.60.1 or uninstalled
 │       │       ├─restricted by compatibility requirements with DiffEqFlux [aae7a2af] to versions: 2.0.0-6.60.1
 │       │       │ └─DiffEqFlux [aae7a2af] log: see above
 │       │       ├─restricted by compatibility requirements with Adapt [79e6a3ab] to versions: [2.0.0-6.4.0, 6.20.0-6.60.1] or uninstalled, leaving only versions: [2.0.0-6.4.0, 6.20.0-6.60.1]
 │       │       │ └─Adapt [79e6a3ab] log: see above
 │       │       ├─restricted by compatibility requirements with DiffEqBase [2b5f629d] to versions: 2.0.0-6.49.1 or uninstalled, leaving only versions: [2.0.0-6.4.0, 6.20.0-6.49.1]
 │       │       │ └─DiffEqBase [2b5f629d] log:
 │       │       │   ├─possible versions are: 3.13.2-6.73.2 or uninstalled
 │       │       │   ├─restricted by compatibility requirements with DiffEqFlux [aae7a2af] to versions: 3.13.2-6.73.2
 │       │       │   │ └─DiffEqFlux [aae7a2af] log: see above
 │       │       │   ├─restricted by compatibility requirements with DataStructures [864edb3b] to versions: 3.13.2-6.44.3 or uninstalled, leaving only versions: 3.13.2-6.44.3
 │       │       │   │ └─DataStructures [864edb3b] log:
 │       │       │   │   ├─possible versions are: 0.9.0-0.18.10 or uninstalled
 │       │       │   │   └─restricted by compatibility requirements with ImageComponentAnalysis [d9b9e9a0] to versions: 0.17.3-0.17.20
 │       │       │   │     └─ImageComponentAnalysis [d9b9e9a0] log: see above
 │       │       │   └─restricted by compatibility requirements with DiffEqFlux [aae7a2af] to versions: 6.41.0-6.73.2, leaving only versions: 6.41.0-6.44.3
 │       │       │     └─DiffEqFlux [aae7a2af] log: see above
 │       │       ├─restricted by compatibility requirements with Flux [587475ba] to versions: [2.0.0-2.4.0, 4.1.0-6.60.1] or uninstalled, leaving only versions: [2.0.0-2.4.0, 4.1.0-6.4.0, 6.20.0-6.49.1]
 │       │       │ └─Flux [587475ba] log: see above
 │       │       ├─restricted by compatibility requirements with DiffEqFlux [aae7a2af] to versions: 6.19.0-6.60.1, leaving only versions: 6.20.0-6.49.1
 │       │       │ └─DiffEqFlux [aae7a2af] log: see above
 │       │       └─restricted by compatibility requirements with Zygote [e88e6eb3] to versions: [2.0.0-5.1.3, 6.22.0-6.60.1] or uninstalled, leaving only versions: 6.22.0-6.49.1
 │       │         └─Zygote [e88e6eb3] log:
 │       │           ├─possible versions are: 0.1.0-0.6.26 or uninstalled
 │       │           ├─restricted by compatibility requirements with Flux [587475ba] to versions: 0.5.0-0.6.26
 │       │           │ └─Flux [587475ba] log: see above
 │       │           └─restricted by compatibility requirements with LoopVectorization [bdcacae8] to versions: [0.1.0-0.5.2, 0.5.14-0.6.26] or uninstalled, leaving only versions: [0.5.0-0.5.2, 0.5.14-0.6.26]
 │       │             └─LoopVectorization [bdcacae8] log:
 │       │               ├─possible versions are: 0.1.0-0.12.85 or uninstalled
 │       │               └─restricted by julia compatibility requirements to versions: 0.9.0-0.12.85 or uninstalled
 │       └─restricted by compatibility requirements with Adapt [79e6a3ab] to versions: 0.11.0-0.12.7 or uninstalled, leaving only versions: 0.11.2-0.12.7
 │         └─Adapt [79e6a3ab] log: see above
 ├─restricted by compatibility requirements with DiffEqFlux [aae7a2af] to versions: 0.6.0-0.6.31
 │ └─DiffEqFlux [aae7a2af] log: see above
 └─restricted by compatibility requirements with Compat [34da2185] to versions: 0.1.0-0.3.2 or uninstalled — no versions left
   └─Compat [34da2185] log:
     ├─possible versions are: 1.0.0-3.39.0 or uninstalled
     └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: 2.0.0-2.2.1
       └─DataFrames [a93c6f00] log: see above

This is the platform info:
julia> versioninfo()
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, cascadelake)

**Comment by zygmuntszpak** [comment]
Should be fixed now,
